name: Run on Pull Request Create

on:
  pull_request:

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Log to Console
        run: echo "You should only be seeing this on pull request create, updated, reopened"
      - name: Test
        run: echo "Hello"
