name: Run on Pull Request Create

on:
  pull_request:

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Log to Console
        run: echo "You should only be seeing this on pull request create, updated, reopened"
  tsc_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install dependencies
        working-directory: ts
        run: yarn install

      - name: Lint tsc
        working-directory: ts
        run: npx tsc --noEmit
